SELECT product_name FROM product;
SELECT product_name, product_price FROM product;
SELECT COLUMNS FROM product;
SELECT product_name, product_price, product_price * 1.12 AS dollars FROM product;
SELECT product_name AS 'Product Name', product_price AS 'Price (Euros)', product_price * 1.12 AS 'Price (USD)' FROM product;
SELECT UPPER(product_name), product_price FROM product;
SELECT LOWER(product_name), product_price FROM product;
SELECT manufacturer_name, UPPER(SUBSTRING(manufacturer_name, 1, 2)) AS 'First two characters' FROM manufacturer;
SELECT product_name, ROUND(product_price) AS product_price FROM product;
SELECT product_name, TRUNCATE(product_price, 0) AS product_price FROM product;
SELECT product_manufacturer_code FROM product;
SELECT DISTINCT product_manufacturer_code FROM product;
SELECT manufacturer_name FROM manufacturer ORDER BY manufacturer_name ASC;
SELECT manufacturer_name FROM manufacturer ORDER BY manufacturer_name DESC;
SELECT product_name FROM product ORDER BY product_name ASC, product_price DESC;
SELECT * FROM manufacturer LIMIT 5;
SELECT * FROM manufacturer LIMIT 2 OFFSET 3;
SELECT product_name, product_price FROM product ORDER BY product_price ASC LIMIT 1;
SELECT product_name, product_price FROM product ORDER BY product_price DESC LIMIT 1;
SELECT product_name FROM product WHERE product_manufacturer_order = 2;
SELECT p.product_name, p.product_price, m.manufacturer_name FROM product p INNER JOIN manufacturer m ON p.product_manufacturer_code = m.manufacturer_code;
SELECT p.product_code, p.product_name, m.manufacturer_code, m.manufacturer_name FROM product p INNER JOIN manufacturere m ON p.product_manufacturer_code = m.manufacturer_code;
SELECT p.product_name, p.product_price, m.manufacturer_name FROM product p INNER JOIN manufacturer m ON p.product_manufacturer_code = m.manufacturer_code ORDER BY p.product_price ASC LIMIT 1;
SELECT p.product_name, p.product_price, m.manufacturer_name FROM product p INNER JOIN manufacturer m ON p.product_manufacturer_code = m.manufacturer_code ORDER BY p.product_price DESC LIMIT 1;
SELECT * FROM product WHERE product_manufacturer_code IN (SELECT manufacturer_code FROM manufacturer WHERE manufacturer_name = 'Lenovo');
SELECT * FROM product WHERE product_manufacturer_code IN (SELECT manufacturer_code FROM manufacturer WHERE manufacturer_name = 'Crucial' AND product_price > 200);
SELECT * FROM product WHERE product_manufacturer_code IN (SELECT manufacturer_code FROM manufacturer WHERE manufacturer_name IN ('Asus', 'Hewlett-Packard', 'Seagate'));
SELECT * FROM product WHERE product_manufacturer_code IN (SELECT manufacturer_code FROM manufacturer WHERE manufacturer_name IN ('Asus', 'Hewlett-Packard', 'Seagate'));
SELECT * FROM product WHERE product_manufacturer_code IN (SELECT manufacturer_code FROM manufacturer WHERE RIGHT(manufacturer_name, 1) = 'e');
SELECT * FROM product WHERE product_manufacturer_code IN (SELECT manufacturer_code FROM manufacturer WHERE manufacturer_name LIKE '%w%');
SELECT p.product_name, p.product_price, m.manufacturer_name FROM product p INNER JOIN manufacturer m ON p.product_manufacturer_code = m.manufacturer_code WHERE p.product_price >= 180 ORDER BY p.product_price DESC, p.product_name ASC;
SELECT m.manufacturer_code, m.manufacturer_name FROM manufacturer m WHERE EXISTS (SELECT 1 FROM product p  WHERE p.product_manufacturer_code = m.manufacturer_code);
SELECT m.manufacturer_name, p.product_name FROM manufacturer m LEFT JOIN product p ON m.manufacturer_code = p.product_manufacturer_code;
SELECT m.manufacturer_name FROM manufacturer m WHERE NOT EXISTS (SELECT 1 FROM product p WHERE p.product_manufacturer_code = m.manufacturer_code);
SELECT * FROM product WHERE product_manufacturer_code IN (SELECT manufacturer_code FROM manufacturer WHERE manufacturer_name = 'Lenovo');
SELECT * FROM product WHERE product_price = (SELECT MAX(product_price) FROM product WHERE product_manufacturer_code IN (SELECT manufacturer_code FROM manufacturer WHERE manufacturer_name = 'Lenovo'));
SELECT product_name FROM product WHERE product_manufacturer_code IN (SELECT manufacturer_code FROM manufacturer WHERE manufacturer_name = 'Lenovo') ORDER BY product_price DESC LIMIT 1;
SELECT product_name FROM product WHERE product_manufacturer_code = (SELECT manufacturer_code FROM manufacturer WHERE manufacturer_name = 'Lenovo') ORDER BY product_price DESC LIMIT 1;
SELECT product_name FROM product WHERE product_manufacturer_code = (SELECT manufacturer_code FROM manufacturer WHERE manufacturer_name = 'Lenovo') ORDER BY product_price ASC LIMIT 1;
SELECT * FROM product WHERE product_price >= (SELECT MAX(product_price) FROM product WHERE product_manufacturer_code = (SELECT manufacturer_code FROM manufacturer WHERE manufacturer_name = 'Lenovo'));
SELECT product_name FROM product WHERE product_manufacturer_code = (SELECT manufacturer_code FROM manufacturer WHERE manufacturer_name = 'Asus') AND product_price > (SELECT AVG(product_price) FROM product WHERE product_manufacturer_code = 
(SELECT manufacturer_code FROM manufacturer WHERE manufacturer_name = 'Asus')) ORDER BY product_price DESC;